In [5]:
include("network_transmission_workplace.jl")
using Profile
using ProfileView
using BenchmarkTools

In [2]:
Params = Dict("ND"=>38, "NL"=>20, "NO"=>10, "NDteams"=>3, "NLteams"=>2, "NOteams"=>2,
                 "is_cohorts"=>true, "Pisol"=>0.5, "Psusc"=>1.0, "p_contact"=>(2.0/(38 + 20 + 10)),
                 "tD"=>0.05,"phi"=>0.1, "InfInit"=>0, "SimType"=>Outbreak_sim,
                 "TeamTimes"=>[0.25,1.0,1.0], "TeamsOutside"=>[true,true,false], 
                 "TeamDistances"=>[2.0,2.0,2.0], "HouseShareFactor"=>0.5, "CarShareFactor"=>0.5)

OccPerDay = ones(90)
NP = 3000*ones(Int64,90)
#if empty args are given, revert to default
PkgParams=DefaultPkgParams
PairParams=DefaultPairParams
TestParams=DefaultTestParams
Incidence = zeros(length(OccPerDay))
Prevalence = zeros(length(OccPerDay))

90-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [14]:
@benchmark run_sim_delivery_wp(P, O, NPh) setup= (P = copy(Params); O = copy(OccPerDay); NPh = copy(NP)) seconds = 600

BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):   3.145 ms … 617.108 ms  ┊ GC (min … max):  0.00% … 11.44%
 Time  (median):     10.651 ms               ┊ GC (median):     0.00%
 Time  (mean ± σ):   19.347 ms ±  21.693 ms  ┊ GC (mean ± σ):  10.19% ± 13.63%

  ▃▇██▇▆▆▅▅▅▄▄▄▄▃▃▂▂▂▂▂▁▁▁  ▁▁   ▁▁  ▁  ▁▁▁▁       ▁           ▃
  ██████████████████████████████████████████████████▇█▇▇▇█▇▇▇▇ █
  3.14 ms       Histogram: log(frequency) by time      93.9 ms <

 Memory estimate: 2.30 MiB, allocs estimate: 16770.

In [19]:
Profile.clear()
Profile.init(delay=1e-6)
@profile run_sim_delivery_wp(Params, OccPerDay, NP)
ProfileView.view()
#best thing to do now is probably to make sure we are not adding unnecessary edges to network

Gtk.GtkWindowLeaf(name="", parent, width-request=-1, height-request=-1, visible=TRUE, sensitive=TRUE, app-paintable=FALSE, can-focus=FALSE, has-focus=FALSE, is-focus=FALSE, focus-on-click=TRUE, can-default=FALSE, has-default=FALSE, receives-default=FALSE, composite-child=FALSE, style, events=0, no-show-all=FALSE, has-tooltip=FALSE, tooltip-markup=NULL, tooltip-text=NULL, window, opacity=1.000000, double-buffered, halign=GTK_ALIGN_FILL, valign=GTK_ALIGN_FILL, margin-left, margin-right, margin-start=0, margin-end=0, margin-top=0, margin-bottom=0, margin=0, hexpand=FALSE, vexpand=FALSE, hexpand-set=FALSE, vexpand-set=FALSE, expand=FALSE, scale-factor=2, border-width=0, resize-mode, child, type=GTK_WINDOW_TOPLEVEL, title="Profile", role=NULL, resizable=TRUE, modal=FALSE, window-position=GTK_WIN_POS_NONE, default-width=800, default-height=600, destroy-with-parent=FALSE, hide-titlebar-when-maximized=FALSE, icon, icon-name=NULL, screen, type-hint=GDK_WINDOW_TYPE_HINT_NORMAL, skip-taskbar-hint

In [ ]:
@benchmark initialise(P, PP, Inc, Prev) setup=
      (P = copy(Params_in); PP = copy(DefaultPairParams); Inc = copy(Incidence); Prev = copy(Prevalence))

In [ ]:
@benchmark init(P, Inc, Prev) setup =
      (P = copy(Params_in); Inc = copy(Incidence); Prev = copy(Prevalence))

In [ ]:
sim = init(Params_in, Incidence, Prevalence)
Nteams = [Params_in["NDteams"],Params_in["NLteams"],Params_in["NOteams"]]
@benchmark generate_cohort_graph!(s, NT, TT, TO, TD) setup = 
    (s = copy(sim); NT = copy(Nteams); TT = copy(Params_in["TeamTimes"]); 
    TO = copy(Params_in["TeamsOutside"]); TD = copy(Params_in["TeamDistances"]))

In [87]:
?fill

search: fill fill! fillopacity fill_preserve set_fill_type finally findall



```
fill(x, dims::Tuple)
fill(x, dims...)
```

Create an array filled with the value `x`. For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with each element initialized to `1.0`.

`dims` may be specified as either a tuple or a sequence of arguments. For example, the common idiom `fill(x)` creates a zero-dimensional array containing the single value `x`.

# Examples

```jldoctest
julia> fill(1.0, (2,3))
2×3 Array{Float64,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0

julia> fill(42)
0-dimensional Array{Int64,0}:
42
```

If `x` is an object reference, all elements will refer to the same object:

```jldoctest
julia> A = fill(zeros(2), 2);

julia> A[1][1] = 42; # modifies both A[1][1] and A[2][1]

julia> A
2-element Array{Array{Float64,1},1}:
 [42.0, 0.0]
 [42.0, 0.0]
```

---

```
fill(gc::GraphicsContext)
```

Fill the current path according to the current fill rule. The current path will be cleared from the context.

See also: [`fill_preserve`](@ref).

---

```
fill(c)
```

Define a fill color, where `c` can be a `Colorant` or `String`.

---

```
fill(cs::AbstractArray)
```

Arguments can be passed in arrays in order to perform multiple drawing operations at once.
